Fixed bugs

diff --git a/bash/fetch4me/fetch4me b/bash/fetch4me/fetch4me
--- a/bash/fetch4me/fetch4me
+++ b/bash/fetch4me/fetch4me
@@ -11,7 +11,7 @@ function lock(){
 		MAX=$[$MAX-1]		
 	done
 	if [ $MAX -eq 0 ] ; then
-		echo "File is locked"
+		echo "Error: File is locked for longtime" >> $QQEDIR/.status
 		exit 1	
 	fi
 	echo $$ > $LOCK
@@ -21,7 +21,7 @@ function lock(){
 function unlock(){
 	LOCK="$1/.fetch4me.lock"
 	if [ ! -f $LOCK ]; then
-		echo "Somebody deleted my files!!!!!!!!"
+		echo "Error: Somebody deleted my files!!!!!!!!" >> $QQEDIR/.status
 		exit 1	
 	fi
 	rm $LOCK
@@ -39,7 +39,7 @@ function finished(){
 # $3 - lock file dir
 function status() {
 	lock $3
-	echo $2 > $1
+	echo "Downloading $2" > $1
 	unlock $3
 }
 
@@ -79,16 +79,16 @@ function downloadLink() {
 
 	status $1/.status $downloadpath $1 
 	if [ $3 ]; then
-		wget -q -P $downloadpath --referer=$3 $2
+		`$GETELEMFUNC -q -P $downloadpath --referer=$3 $2`
 	else
-		wget -q -P $downloadpath $2
+		`$GETELEMFUNC -q -P $downloadpath $2`
 	fi
 	if [ $? -ne 0 ]; then
-		echo "Wget error"
+		echo "Error: problem with processing $2 via $GETLEMFUNC to $downloadpath" >> $1/.status
 		exit 1
 	fi
 	finished $1/.finished $2 $3
-	status $1/.status "downloaded" $1 
+	status $1/.status "ended" $1 
 	return 0
 }
 
@@ -102,13 +102,13 @@ function run {
 		
 		for url in ${urls[@]};
 		do
-			downloadlink $1 $url $2			
+			downloadLink $1 $url $2			
 		done
 		
 		lock $1
 		echo > $1/.queue
 		unlock $1
-		sleep 100
+		sleep 10
 	done		
 }
 
@@ -116,23 +116,27 @@ function run {
 function daemonazing(){
 	PID="$1/.fetch4me.pid"
 	if [ -f $PID ]; then
-		echo "Daemon was here"
+		echo "Other daemon was here"
 		read pid < $PID				
-		isAlive=`ps $pid | grep $pid | grep 'fetch4me' | awk '{ print $1; }'`
+		isAlive=`ps $pid | grep $pid | awk '{ print $1; }'`
 		if [ -z $isAlive ]; then
-			echo "Daemon was crashed"
-			#rescue links
+			echo "Other daemon was crashed"
+			#adding interrupted link
+			url=`cat $1/.status | awk '{ split ($0, arr, "="); print arr[2]; }'`
+			if [ $url ]; then
+				echo $URL >> $QQEDIR/.queue
+			fi
 		else
-			echo "Daemon is alive. I will die"
+			echo "Other daemon is alive. I will die"
 			exit 0
 		fi
 	else 
-		echo "daemon doesn't exist"
+		echo "Other daemon doesn't exist"
 	fi
 	
 	#daemonizing)
 	echo $$ > $1/.fetch4me.pid 
-	#trap...			
+	trap "echo 'I am alive!!!!!'" SIGHUP		
 }
 
 #TODO bad reading need "~/.fetch4me"
@@ -167,13 +171,14 @@ fi
 echo "QQEDIR = $QQEDIR"
 echo "GETELEMFUNC=$GETELEMFUNC"
 echo "REFFER=$REFFER"
+echo "My pid is $$, but i want live"
 
 if [ ! -d $QQEDIR ]; then
-	echo "QQEDIR doesn't  exist: $QQEDIR"
+	echo "QQEDIR doesn't  exist: $QQEDIR" >> $QQEDIR/.status
 	exit 1 
 fi 
 if [ -z `which $GETELEMFUNC | awk '{ print $1; }'` ]; then 
-	echo "GETELEMFUNC doesn't exist: $GETELEMFUNC"
+	echo "GETELEMFUNC doesn't exist: $GETELEMFUNC" >> $QQEDIR/.status
 	exit 1
 fi
 
@@ -188,7 +193,6 @@ for ((i=$FIRSTARG; i<${#ARGS[@]}; i++)); do
 done
 unlock $QQEDIR
 
-echo $$
 daemonazing $QQEDIR
 run $QQEDIR $REFFER
 
