It works partially

diff --git a/bash/fetch4me/fetch4me b/bash/fetch4me/fetch4me
--- a/bash/fetch4me/fetch4me
+++ b/bash/fetch4me/fetch4me
@@ -1,42 +1,142 @@
 
 #!/bin/bash
-<<<<<<< HEAD
 
-# $1 - link to download
-# $2 - optional referer link
+# $1 - lock file dir
+function lock(){
+	#TODO semaphors"
+	LOCK="$1/.fetch4me.lock"	
+	MAX=500
+	while [ -f $LOCK ] && [ $MAX -gt 0 ] ; do
+		sleep 0.01	
+		MAX=$[$MAX-1]		
+	done
+	if [ $MAX -eq 0 ] ; then
+		echo "File is locked"
+		exit 1	
+	fi
+	echo $$ > $LOCK
+}
+
+# $1 - lock file dir
+function unlock(){
+	LOCK="$1/.fetch4me.lock"
+	if [ ! -f $LOCK ]; then
+		echo "Somebody deleted my files!!!!!!!!"
+		exit 1	
+	fi
+	rm $LOCK
+}
+
+# $1 - finished file
+# $2 - link
+# $3 - referer. optional
+function finished(){
+	echo "`date +%s` $3 $2" >> $1
+}
+
+# $1 - status file
+# $2 - downloading file
+# $3 - lock file dir
+function status() {
+	lock $3
+	echo $2 > $1
+	unlock $3
+}
+
+# $1 - QQEDIR
+# $2 - link to download
+# $3 - optional referer link
 function downloadLink() {
 	DOWNLOADPATH=~/Downloads/fetched4you
-	echo $DOWNLOADPATH
-	if  [ ! -d $DOWNLOADPATH ]; then
-		echo 1
-		mkdir $DOWNLOADPATH
-		echo "Created fetched4you"
-	fi
-	exit 0	
-	if [ $2 ]; then
-		donwloadpath=$DOWNLOADPATH/'"'$2'"'
-		if [ ! -d $downloadpath ]; then
-			mkdir $downloadpath
-			echo "Created $2"	
-		fi
-		downloadpath=$downloadpath/'"'$1'"'
-		if [ ! -d $downloadpath ]; then
-			mkdir $donwloadpath
-			echo "Created $1"
-		fi
-		wget -P $downloadpath --referer=$2 $1
-	else
-		downloadpath=$DOWNLOADPATH/'"'$1'"'		
-		wget -P $downloadpath--referer=$2 $1	
-	fi
-	echo $downloadpath
 
+	if  [ ! -d $DOWNLOADPATH ]; then
+		echo "Created fetched4you"		
+		mkdir $DOWNLOADPATH	
+	fi
+
+	referDir=${3//'http://'/''} 
+	referDir=${referDir//'\'/'_'} 
+	referDir=${referDir//' '/'_'}	
+	referDir=${referDir//'\'/'_'} 
+	downloadpath=$DOWNLOADPATH
+	if [ $3 ]; then
+		downloadpath=$downloadpath/$referDir
+		if [ ! -d $downloadpath ]; then
+				echo "Created referer $3"	
+				mkdir $downloadpath
+		fi
+	fi
+
+	pageDir=${2//'http://'/''} 
+	pageDir=${pageDir//'/'/'_'} 
+	pageDir=${pageDir//'\'/'_'} 
+	pageDir=${pageDir//'\'/'_'}
+	downloadpath=$downloadpath/$pageDir
+	if [ ! -d $downloadpath ]; then
+		echo "Created page $2"
+		mkdir $downloadpath		
+	fi
+
+	status $1/.status $downloadpath $1 
+	if [ $3 ]; then
+		wget -q -P $downloadpath --referer=$3 $2
+	else
+		wget -q -P $downloadpath $2
+	fi
+	if [ $? -ne 0 ]; then
+		echo "Wget error"
+		exit 1
+	fi
+	finished $1/.finished $2 $3
+	status $1/.status "downloaded" $1 
 	return 0
 }
 
-=======
->>>>>>> 63ba6ad68d9c14adb0846173fecc11bbf43a4dfc
+# $1 - QQEDIR
+# $2 - referer
+function run {
+	while [ 1 -ne 0 ] ; do
+		lock $1
+		urls=`cat $1/.queue`
+		unlock $1
+		
+		for url in ${urls[@]};
+		do
+			downloadlink $1 $url $2			
+		done
+		
+		lock $1
+		echo > $1/.queue
+		unlock $1
+		sleep 100
+	done		
+}
+
+# $1 - QQEDIR
+function daemonazing(){
+	PID="$1/.fetch4me.pid"
+	if [ -f $PID ]; then
+		echo "Daemon was here"
+		read pid < $PID				
+		isAlive=`ps $pid | grep $pid | grep 'fetch4me' | awk '{ print $1; }'`
+		if [ -z $isAlive ]; then
+			echo "Daemon was crashed"
+			#rescue links
+		else
+			echo "Daemon is alive. I will die"
+			exit 0
+		fi
+	else 
+		echo "daemon doesn't exist"
+	fi
+	
+	#daemonizing)
+	echo $$ > $1/.fetch4me.pid 
+	#trap...			
+}
+
 #TODO bad reading need "~/.fetch4me"
+
 QQEDIR=`cat ~/.fetch4merc | grep QQEDIR | awk '{ split ($0, arr, "="); print arr[2]; }'`
 GETELEMFUNC=`cat ~/.fetch4merc | grep GETELEMFUNC | awk '{ split ($0, arr, "="); print arr[2]; }'`
 FIRSTARG=0
@@ -56,7 +156,6 @@ elif [ "$1" = "-r" ]; then
 		FIRSTARG=4
 	fi
 fi
-
 if [ -z $QQEDIR ]; then
 	QQEDIR="~/.fetch4me"
 fi 	
@@ -69,16 +168,6 @@ echo "QQEDIR = $QQEDIR"
 echo "GETELEMFUNC=$GETELEMFUNC"
 echo "REFFER=$REFFER"
 
-for X in "$@"
-do
-  echo ${!X}
-done
-
-#ARGS=("$@")
-#for (( i=$FIRSTARG; i<${#ARGS[@]}; i++)); do
-#    echo ${ARGS[${i}]}
-#done 
-
 if [ ! -d $QQEDIR ]; then
 	echo "QQEDIR doesn't  exist: $QQEDIR"
 	exit 1 
@@ -88,82 +177,18 @@ if [ -z `which $GETELEMFUNC | awk '{ print $1; }'` ]; then
 	exit 1
 fi
 
-##
-## TODO: check, if REFERRER is correct URL. If not - exit 1.
-##
 
-PID="$QQEDIR/fetch4me.pid"
-LOCK="$QQEDIR/fetch4me.lock"
-<<<<<<< HEAD
 
-downloadLink http://yahoo.com http://by.com
- 
-if [ -f $PID ]; then
-	echo "Daemon exist"
-	read pid < $PID	
-	isAlive=`ps $pid | grep $pid | grep 'fetch4me' | awk '{ print $1; }'`
-	if [ -z $isAlive ]; then
-		echo "Daemon was crashed"
-		#TODO add links
-	else
-		echo "Daemon is alive. I will die"
-		#TODO add links
-		exit 0
-=======
-echo $PID
-if [ -e $PID ]; then
-	echo "Daemon exist"
-	read pid < $PID	
-	isAlive=`ps $pid | grep $pid | awk '{ print $1; }'`
-	if [ -z $isAlive ]; then
-		echo "Daemon was crashed"
-	else
-		echo "Daemon is alive. I will die"
->>>>>>> 63ba6ad68d9c14adb0846173fecc11bbf43a4dfc
-	fi
+#adding links
+ARGS=("$@")
+lock $QQEDIR
+for ((i=$FIRSTARG; i<${#ARGS[@]}; i++)); do
+	URL=${ARGS[$i]}
+	echo $URL >> $QQEDIR/.queue
+done
+unlock $QQEDIR
 
-else
-	echo "Daemon doesn't exist"
-	#trap "echo 'fuck off'" SIGHUP
-fi
-<<<<<<< HEAD
+echo $$
+daemonazing $QQEDIR
+run $QQEDIR $REFFER
 
-=======
->>>>>>> 63ba6ad68d9c14adb0846173fecc11bbf43a4dfc
-##
-## TODO: search for "fetch4me.lock" in QQEDIR, if there is one - 
-## look at PID and find out, is the daemon running or has it crashed
-## If process is running - add new files to QQEDIR and exit 0. If not - try to 
-## restart unfinished downloads, generate new lock file. Daemonize.
-## If there's new lock file - generate new queue, daemonize.
-##
-
-##
-## TODO: process all files from QQEDIR
-##
-
-##
-## TODO: 'df -h' to find out, if there's enough space on disk. If not - exit 1.
-##
-
-<<<<<<< HEAD
-=======
-##
-## Below is some shit for copy-pasting useful code)
-##
-
-aaa=`ps -e | grep fetch4me | grep -v "grep" | awk '{print $1;}'`
-echo $aaa
-if [ -z "$aaa" ]; then
-	echo "daemon is already running"
-else
-	echo "trap"
-	#trap "echo 'fuck off'" SIGHUP
-fi
-#while [ 1 -gt 0 ]; do
-#	sleep 1;
-#done
-function downloadLink() {
-	echo 1
-}
->>>>>>> 63ba6ad68d9c14adb0846173fecc11bbf43a4dfc
